Feature: added cloudbuild test and deploy scripts
sendahug/send-hug-backend pull request #626
Opened 2024-05-07 08:44 UTC by danted22

Needs the terraform setup to be created first

2024-05-07 08:47 UTC, danted22 commented
Part of https://github.com/sendahug/internal/issues/21

2024-06-01 18:39 UTC, shirblc commented
Just so we don't forget: we also need to add a docker file in this PR...

2024-06-17 19:36 UTC, danted22 reviewed
This is good to go!

2024-06-18 17:05 UTC, shirblc approved these changes

2024-06-18 17:05 UTC, shirblc requested changes
I think there's a missing Changelog? 🤨🧐

2024-06-18 17:20 UTC, danted22 commented
Oops there is. Will add after twins bedtime!

2024-06-18 18:46 UTC, danted22 commented
Added 😀

2024-06-21 09:29 UTC, shirblc approved these changes

2024-06-21 09:29 UTC, shirblc commented on changelog/pr626.json
> +            "description": "Added Dockerfile for containserszation of the app for deployment"
I think that was supposed to be containerisation 😉

2024-06-21 09:32 UTC, merged