Feature: added ability to send emails
sendahug/send-hug-backend pull request #701
Opened 2024-12-06 13:20 UTC by danted22

2024-12-08 19:05 UTC, shirblc requested changes

2024-12-08 19:05 UTC, shirblc commented on tests/test_utils.py
> +@pytest.mark.skip("Not running as it sends emails")
Can you replace this with a real test? Appreciate there's not much in it, but still

2024-12-08 19:05 UTC, shirblc commented on utils/email.py
> +import os
License please!

2024-12-08 19:05 UTC, shirblc commented on utils/email.py
> +def send(to: str, subject: str, content: str, from_email: str = DEFAULT_FROM):
Can you add a docstring?

2025-01-19 17:20 UTC, shirblc requested changes

2025-01-19 17:20 UTC, shirblc commented on cloudbuild-staging.yaml
>          --update-secrets PRIVATE_VAPID_KEY=private_vapid_key:latest
Isn't it missing a `\`? I just did a double take seeing the difference between the two files

2025-01-19 17:20 UTC, shirblc commented on controllers/posts.py
> +        await send_notifications(user_id=post_author.id, data=push_notification)
I'm not sure that's what we want here. Didn't we say that in the first stage, we'll only be sending individual emails for messages?

2025-01-19 17:20 UTC, shirblc commented on controllers/users.py
> +    await send_notifications(user_id=user_to_hug.id, data=push_notification)
Same here.

2025-01-19 17:20 UTC, shirblc commented on tests/test_utils.py
> +def test_email_send_for_reals() -> None:
Not sure we need this if it's not actually running

2025-01-19 17:20 UTC, shirblc commented on tests/test_utils.py
> +# Email tests
I think the function in common.py should also be tested

2025-01-19 17:20 UTC, shirblc commented on utils/email.py
> +def send(
A more descriptive name would probably make things easier

2025-01-19 17:20 UTC, shirblc commented on changelog/pr701.json
> +      "description": "Switched out send push notifications code for code that sends both push and email notifications."
Can this be rephrased? "Switched out send push notifications code for code ..." feels a little convoluted and complicated to follow... (I know, semantics, but still)

2025-02-06 19:25 UTC, danted22 commented on cloudbuild-staging.yaml
>          --update-secrets PRIVATE_VAPID_KEY=private_vapid_key:latest
oops!

2025-02-06 19:26 UTC, danted22 commented on controllers/posts.py
> +        await send_notifications(user_id=post_author.id, data=push_notification)
yeah, I just did a blind find replace which was probably stupid

2025-02-06 19:27 UTC, danted22 commented on controllers/users.py
> +    await send_notifications(user_id=user_to_hug.id, data=push_notification)
yeah, as above

2025-02-06 19:29 UTC, danted22 commented on tests/test_utils.py
> +def test_email_send_for_reals() -> None:
disagree, we should run it manually if the sendgrid library is updated - I've updated the skip message though to make that clearer

2025-02-06 19:30 UTC, danted22 commented on utils/email.py
> +def send(
updated

2025-02-06 19:31 UTC, danted22 commented on changelog/pr701.json
> +      "description": "Switched out send push notifications code for code that sends both push and email notifications."
updated, hope it's better!

2025-02-06 20:47 UTC, danted22 commented on tests/test_utils.py
> +# Email tests
added (although none of the other common functions are tested 😛 , but i do realise we need to start somewhere 😁 )

2025-03-08 17:13 UTC, shirblc commented on tests/test_utils.py
> +# Email tests
I could've sworn we had tests for at least one of those, but I can't find it at a glance... 🤔

2025-03-08 17:19 UTC, shirblc commented on tests/test_utils.py
> +def test_email_send_for_reals() -> None:
I have two problems with this:
- I don't think we'll actually remember to run it when there's a library update
- I'm not sure a manually-running test belongs with the rest of our tests

I take your point about needing something to simply run a simple request, as opposed to running the API locally (especially because it's not possible to message yourself so testing it locally would have to involve two different accounts), but I'm still not sure it's the right place for it

2025-03-08 17:19 UTC, shirblc commented on controllers/posts.py
> +        await send_notifications(user_id=post_author.id, data=push_notification)
happens to everyone!

2025-03-08 17:20 UTC, shirblc commented on changelog/pr701.json
> +      "description": "Switched out send push notifications code for code that sends both push and email notifications."
Definitely!

2025-03-09 07:25 UTC, danted22 commented on tests/test_utils.py
> +def test_email_send_for_reals() -> None:
Hmm, good point. I always have the best of intentions with these manual tests but then never run them.

I'll remove and have a think of a better place for stuff like this.

2025-03-10 20:44 UTC, shirblc commented on tests/test_utils.py
> +def test_email_send_for_reals() -> None:
I was thinking today that maybe we can have a mark for it? Then if a specific flag is set (e.g., if the package is updated), it runs it automatically in CI? I'm not sure that's doable though. We'd probably need to add some secrets to CI and I don't even know how that'd work based on dependencies...

2025-03-10 20:46 UTC, shirblc approved these changes

2025-03-10 20:46 UTC, merged